version: '3'
services:
  movie-searcher-server:
    container_name: movie-searcher-server
    build:
      context: ./movie-searcher-server
    ports:
      - 8080:8080
  movie-searcher-client:
    container_name: movie-searcher-client
    build:
      context: ./movie-searcher-client
      args:
        - API_URL=localhost
        - API_PORT=8080
    ports:
      - 9090:80
